django_todo/urls.py
from django.contrib import admin
from django.urls import path
from todo.views import get_todo_list, add_item, edit_item, toggle_item, delete_item
# an alternative way to import these function from views.py would be 'import views', and then prepend views. to each function call - i.e. views.add_item

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', get_todo_list, name='get_todo_list'),
    path('add', add_item, name='add'),
    path('edit/<item_id>', edit_item, name='edit'),
    path('toggle/<item_id>', toggle_item, name='toggle'),
    path('delete/<item_id>', delete_item, name='delete')
]

# the hello path calls the say_hello function in todo/views.py
# when running the server, /hello must be appended to the url in the url bar
# this will render a simple html page with the text 'hello'
# the third entry, add, corresponds to the href of the anchor tag in todo_list.html
# in the fourth entry, the angular bracket takes in the item's id and this is the way by which an id make its way from a link or form, through the URL and into the view
# in views.py, item_id is a paramter in the edit_item function

todo/models.py
from django.db import models

# Create your models here.


class Item(models.Model):  # inherits the model class, which is supplied by Django
    name = models.CharField(max_length=50, null=False, blank=False)
    done = models.BooleanField(null=False, blank=False, default=False)


    def __str__(self):
        return self.name



# name is a character field, so it can only contain text characters in it. max_length specifies the maximum number of characters
# null=False prevents the creation of records without an entry in the name field
# blank=False makes the name field required on all forms
# specifying these here means that the onus of checking is transferred to the database, not on whatever submits the information to create the record
# This is because tasks can be added using a web form or via the Django database
# done is a Boolean field, so it can only contain values of True or False
# default=False means that items are marked with False in the done column by default
# the __str__ function overrides the base model class string method that creates the name of the record in the table
# By default, this string method provides a generic, unhelpful name that makes it difficult to find records in the database
# Overriding the string method to produce a custom name as above makes it much easier to navigate the table
# These changes do not need to be committed in any way - saving and hard-refreshing does the trick 

todo/forms.py
# This file handles form validation

from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'done']



# ItemForm is a class and inherits all of the functionality of the pre-built ModelForm from forms
# Meta is an inner class
# 

todo/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from .models import Item
from .forms import ItemForm


# Create your views here.


def get_todo_list(request):
    items = Item.objects.all()
    context = {
        'items': items
    }
    return render(request, 'todo/todo_list.html', context)
# The standard way to render an HTML document
# the items variable holds all of the entries in the Items table of the database
# These items can be displayed by adding them to the context dictionary and passing context to the return render statement


def add_item(request):
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('get_todo_list')
        # name = request.POST.get('item_name')
        # done = 'done' in request.POST
        # Item.objects.create(name=name, done=done)
        # the commented out lines refer to a previous build which processed a form we created ourselves
        # since we are now using a standard pre-built Django form, we need to use the above syntax
        # the is_valid method checks to see if the submitted form is valid per the blank and null statements in the models.py file

    form = ItemForm()
    context = {
        'form': form
    }
    return render(request, 'todo/add_item.html', context)

# the if statement in add_item handles users submitting the form. The name and done variables grab the values from the form object using the input name attributes
# An actual entry in the database is created using the Item.object.create method
# name=name and done=done are a bit confusing, but this because the variable names match the variables in the Item model and hence the column headers in the database
# This is both the benefit and curse of using harmonised syntax
# the return redirect command redirects the user to the todo items page, so that they can view their updated items


def edit_item(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('get_todo_list')
    form = ItemForm(instance=item)
    context = {
        'form': form
    }
    return render(request, 'todo/edit_item.html', context)

# get_object_or_404 is a Django shortcut and is used when we want to get an instance of the Item model
# form = ItemForm(instance=item) is used as in add_item, but instance=item pre-populates the form


def toggle_item(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    item.done = not item.done
    item.save()
    return redirect('get_todo_list')


# item.done = not item.done flips the done status from whatever it currently is, i.e. false to true
# this function then saves and redirects back to the list of items
# whilst it may not seem like it, the page does actually do things and does refresh, but it is very quick


def delete_item(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    item.delete()
    return redirect('get_todo_list')

todo/templates/todo/add_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add item</title>
</head>
<body>
    <h1>
        Add a To Do item
    </h1>
    <form action="add" method="POST">
        {% csrf_token %}
        <!--csrf_token means 'cross-site request forgery token' 
        and is added to the submitted form object to guarantee that submissions are coming from this app, and not somewhere else-->
        <!--<div>
            <p>
                <label for="id_name">Name</label>
                <input type="text" name="item_name" id="id_name">
            </p>
        </div>
        <div>
            <p>
                <input type="checkbox" name="done" id="id_done">
                <label for="id_done">Done</label>
            </p>
        </div>-->
        {{ form.as_p }}
        <!--form is not a database table, but is a standard Django form, defined in forms.py and in the add_item function in views.py-->
        <!--The as_p method renders the form's inputs inside individual p elements-->
        <div>
            <p>
                <button type="submit">Add Item</button>
            </p>
        </div>
    </form>
</body>
</html>

todo/templates/todo/edit_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit entry</title>
</head>
<body>
    <h1>
        Edit an item
    </h1>
    <form method="POST"><!--Note the lack of action=add. This will cause the form to post to the same URL-->
        {% csrf_token %}
        <!--csrf_token means 'cross-site request forgery token' 
        and is added to the submitted form object to guarantee that submissions are coming from this app, and not somewhere else-->
        
        {{ form.as_p }}
        <!--form is not a database table, but is a standard Django form, defined in forms.py and in the add_item function in views.py-->
        <!--The as_p method renders the form's inputs inside individual p elements-->
        <div>
            <p>
                <button type="submit">Update Item</button>
            </p>
        </div>
    </form>
</body>
</html>

todo/templates/todo/todo_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To Do List</title>
</head>
<body>
    <h1>
        Things to do
    </h1>

    <!--{{ items }}
    This displays any entries in the Items table, but not in a user friendly way-->
    
        <table>
            {% for item in items %}
            <tr>
                {% if  item.done == True %}
                    <td><strike>{{ item.name }}</strike></td>
                {% else %}
                    <td>{{ item.name }}</td>
                {% endif %}
                <td>
                    <a href="/toggle/ {{  item.id }}">
                        <button>Toggle status</button>
                    </a>
                </td>
                <td>
                    <a href="/edit/ {{  item.id }}">
                        <button>Edit item</button>
                    </a>
                </td>
                <td>
                    <a href="/delete/ {{  item.id }}">
                        <button>Delete item</button>
                        <!--As with the Flask Task Manager app, applying some sort of checking or confirmation function via a modal would be used-->
                    </a>
                </td>
            </tr>    
            {% empty %}
            <tr><td>No items in database Items table</td></tr>
            {% endfor %}
            <!--This is Django's version of Jinja, which works similarly to Jinja in Flask-->
            <!--The item.done == True syntax is verbose, but clearer to be. == True could be removed-->
            <!--The empty tag is a failsafe for displaying something if the Items table is empty-->
    </table>
    <a href="/add">Add an item</a>
</body>
</html>